# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u672c\u5730\u5206\u6790\u7f16\u53f7')),
                ('status', models.CharField(choices=[('InProgress', '\u8fdb\u884c\u4e2d'), ('canceled', '\u5df2\u53d6\u6d88'), ('finished', '\u5df2\u5b8c\u7ed3')], default='InProgress', max_length=10, verbose_name='\u5206\u6790\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u6790\u4fe1\u606f',
                'verbose_name_plural': '\u5206\u6790\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u8ba2\u5355\u540d\u79f0')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('status', models.CharField(choices=[('InProgress', '\u8fdb\u884c\u4e2d'), ('canceled', '\u5df2\u53d6\u6d88'), ('finished', '\u5df2\u5b8c\u7ed3')], default='InProgress', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('pay_status', models.CharField(choices=[('unpaied', '\u672a\u652f\u4ed8'), ('paid', '\u5df2\u652f\u4ed8')], default='unpaied', max_length=10, verbose_name='\u4ed8\u8d39\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u672c\u5730\u5b9e\u9a8c\u7f16\u53f7')),
                ('CRO_name', models.CharField(default='', max_length=100, verbose_name='\u5916\u5305\u5b9e\u9a8c\u7f16\u53f7')),
                ('experiment_type', models.CharField(choices=[('WES', '\u5168\u5916\u663e\u5b50\u6d4b\u5e8f'), ('TS', 'RNA\u6d4b\u5e8f')], default='WES', max_length=15, verbose_name='\u5b9e\u9a8c\u7c7b\u578b')),
                ('express_company', models.CharField(choices=[('SF', '\u987a\u4e30\u5feb\u9012'), ('YT', '\u5706\u901a\u5feb\u9012'), ('ST', '\u7533\u901a\u5feb\u9012'), ('YD', '\u97f5\u8fbe\u5feb\u9012')], default='SF', max_length=10, verbose_name='\u5feb\u9012\u516c\u53f8')),
                ('express_number', models.CharField(max_length=20, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('status', models.CharField(choices=[('InProgress', '\u8fdb\u884c\u4e2d'), ('canceled', '\u5df2\u53d6\u6d88'), ('finished', '\u5df2\u5b8c\u7ed3')], default='InProgress', max_length=10, verbose_name='\u5b9e\u9a8c\u72b6\u6001')),
                ('pay_status', models.CharField(choices=[('unpaied', '\u672a\u652f\u4ed8'), ('paid', '\u5df2\u652f\u4ed8')], default='unpaied', max_length=10, verbose_name='\u652f\u4ed8\u72b6\u6001')),
                ('result_status', models.CharField(choices=[('success', '\u6210\u529f'), ('fail', '\u5931\u8d25')], default='success', max_length=10, verbose_name='\u5b9e\u9a8c\u7ed3\u679c')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Deal', verbose_name='\u5bf9\u5e94\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u5b9e\u9a8c\u4fe1\u606f',
                'verbose_name_plural': '\u5b9e\u9a8c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u75c5\u4eba\u7f16\u53f7')),
                ('nick_name', models.CharField(default='', max_length=50, verbose_name='\u59d3\u540d')),
                ('age', models.IntegerField(default=0, verbose_name='\u5e74\u9f84')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973'), ('unknown', '\u672a\u77e5')], default='unknown', max_length=10, verbose_name='\u6027\u522b')),
                ('id_card', models.CharField(max_length=18, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u5730\u5740')),
                ('diagnosis', models.CharField(default='', max_length=100, verbose_name='\u8bca\u65ad\u7ed3\u679c')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u75c5\u4eba\u4fe1\u606f',
                'verbose_name_plural': '\u75c5\u4eba\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u672c\u5730\u5408\u6210\u7f16\u53f7')),
                ('CRO_name', models.CharField(default='', max_length=100, verbose_name='\u5916\u5305\u5408\u6210\u7f16\u53f7')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('status', models.CharField(choices=[('InProgress', '\u8fdb\u884c\u4e2d'), ('canceled', '\u5df2\u53d6\u6d88'), ('finished', '\u5df2\u5b8c\u7ed3')], default='InProgress', max_length=10, verbose_name='\u5408\u6210\u72b6\u6001')),
                ('pay_status', models.CharField(choices=[('unpaied', '\u672a\u652f\u4ed8'), ('paid', '\u5df2\u652f\u4ed8')], default='unpaied', max_length=10, verbose_name='\u652f\u4ed8\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('analysis', models.ManyToManyField(to='neoatigen.Analysis', verbose_name='\u5bf9\u5e94\u5206\u6790')),
            ],
            options={
                'verbose_name': '\u591a\u80bd\u4fe1\u606f',
                'verbose_name_plural': '\u591a\u80bd\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u672c\u5730\u6837\u672c\u7f16\u53f7')),
                ('original_name', models.CharField(default='', max_length=100, verbose_name='\u539f\u59cb\u6837\u672c\u7f16\u53f7')),
                ('sample_type', models.CharField(choices=[('FFPE', '\u8721\u5757'), ('BLOOD', '\u5168\u8840'), ('FreshTissue', '\u65b0\u9c9c\u7ec4\u7ec7'), ('WhiteParaffinSlice', '\u767d\u7247')], max_length=15, verbose_name='\u6837\u672c\u7c7b\u578b')),
                ('num', models.IntegerField(default=1, verbose_name='\u6570\u91cf')),
                ('units', models.CharField(choices=[('block', '\u5757'), ('piece', '\u7247'), ('tube', '\u7ba1')], max_length=15, verbose_name='\u5355\u4f4d')),
                ('site', models.CharField(default='', max_length=50, verbose_name='\u53d6\u6837\u90e8\u4f4d')),
                ('location', models.CharField(default='', max_length=50, verbose_name='\u6837\u54c1\u4fdd\u5b58\u4f4d\u7f6e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5230\u6837\u65f6\u95f4')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba')),
            ],
            options={
                'verbose_name': '\u6837\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u6837\u672c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u75ab\u82d7\u5236\u5907\u7f16\u53f7')),
                ('status', models.CharField(choices=[('InProgress', '\u8fdb\u884c\u4e2d'), ('canceled', '\u5df2\u53d6\u6d88'), ('finished', '\u5df2\u5bc4\u51fa')], default='InProgress', max_length=10, verbose_name='\u5236\u5907\u72b6\u6001')),
                ('express_company', models.CharField(choices=[('SF', '\u987a\u4e30\u5feb\u9012'), ('YT', '\u5706\u901a\u5feb\u9012'), ('ST', '\u7533\u901a\u5feb\u9012'), ('YD', '\u97f5\u8fbe\u5feb\u9012')], default='SF', max_length=10, verbose_name='\u5feb\u9012\u516c\u53f8')),
                ('express_number', models.CharField(max_length=20, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('peptide', models.ManyToManyField(to='neoatigen.Peptide', verbose_name='\u5bf9\u5e94\u5206\u6790')),
            ],
            options={
                'verbose_name': '\u75ab\u82d7\u4fe1\u606f',
                'verbose_name_plural': '\u75ab\u82d7\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='specimen',
            field=models.ManyToManyField(to='neoatigen.Specimen', verbose_name='\u5bf9\u5e94\u6837\u672c'),
        ),
        migrations.AddField(
            model_name='deal',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='experiment',
            field=models.ManyToManyField(to='neoatigen.Experiment', verbose_name='\u5bf9\u5e94\u5b9e\u9a8c'),
        ),
    ]
