# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='CRO_company',
            field=models.CharField(choices=[('WuXi', '\u836f\u660e\u5eb7\u5fb7'), ('NovoGene', '\u8bfa\u79be\u81f4\u6e90'), ('CloudHealth', '\u4e91\u5065\u5eb7')], default='WuXi', max_length=50, verbose_name='\u5916\u5305\u516c\u53f8\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='CRO_company',
            field=models.CharField(choices=[('gl', '\u5409\u5c14'), ('cp', '\u4e2d\u80bd')], default='glb', max_length=50, verbose_name='\u5916\u5305\u516c\u53f8\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='num',
            field=models.IntegerField(default=5, verbose_name='\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='unit',
            field=models.CharField(choices=[('mg', '\u6beb\u514b'), ('g', '\u514b')], default='mg', max_length=10, verbose_name='\u5355\u4f4d'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('InProgress', '\u914d\u5236\u4e2d'), ('canceled', '\u5df2\u53d6\u6d88'), ('finished', '\u5df2\u5b8c\u6210'), ('sent', '\u5df2\u5bc4\u51fa')], default='InProgress', max_length=10, verbose_name='\u5236\u5907\u72b6\u6001'),
        ),
    ]
