# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0002_auto_20190123_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='invoice',
            field=models.CharField(default='', max_length=20, verbose_name='\u53d1\u7968\u53f7'),
        ),
    ]
