# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0003_deal_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptide',
            name='quantity',
            field=models.IntegerField(default=5, verbose_name='\u5355\u6761\u591a\u80bd\u8ba2\u8d2d\u91cf'),
        ),
        migrations.AlterField(
            model_name='peptide',
            name='num',
            field=models.IntegerField(default=0, verbose_name='\u591a\u80bd\u6761\u6570'),
        ),
    ]
