# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0004_auto_20190123_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='result_status',
            field=models.CharField(choices=[('unknown', '\u672a\u77e5'), ('success', '\u6210\u529f'), ('fail', '\u5931\u8d25')], default='unknown', max_length=10, verbose_name='\u5b9e\u9a8c\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u8bca\u65ad\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='peptide',
            field=models.ManyToManyField(to='neoatigen.Peptide', verbose_name='\u5bf9\u5e94\u591a\u80bd'),
        ),
    ]
