# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0006_auto_20190123_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='CRO_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5916\u5305\u5b9e\u9a8c\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='peptide',
            name='CRO_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5916\u5305\u5408\u6210\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u6837\u54c1\u4fdd\u5b58\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u539f\u59cb\u6837\u672c\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='site',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u53d6\u6837\u90e8\u4f4d'),
        ),
    ]
