# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0007_auto_20190123_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba'),
        ),
    ]
