# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0009_auto_20190123_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='deal',
        ),
        migrations.AddField(
            model_name='experiment',
            name='deal',
            field=models.ManyToManyField(to='neoatigen.Deal', verbose_name='\u5bf9\u5e94\u8ba2\u5355'),
        ),
    ]
