# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-24 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0010_auto_20190123_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='sample_type',
            field=models.CharField(choices=[('FFPE', '\u8721\u5757'), ('BLOOD', '\u5168\u8840'), ('FreshTissue', '\u65b0\u9c9c\u7ec4\u7ec7'), ('ParaffinSlice', '\u767d\u7247')], max_length=15, verbose_name='\u6837\u672c\u7c7b\u578b'),
        ),
    ]
