# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0012_auto_20190124_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('InProgress', '\u8fdb\u884c\u4e2d'), ('canceled', '\u5df2\u53d6\u6d88'), ('finished', '\u5df2\u5b8c\u6210'), ('sent', '\u5df2\u5bc4\u51fa')], default='InProgress', max_length=10, verbose_name='\u5236\u5907\u72b6\u6001'),
        ),
    ]
