# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-22 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0013_auto_20190124_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba'),
        ),
    ]
