# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0015_auto_20190227_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='peptide',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
