# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0016_auto_20190228_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='express_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5feb\u9012\u5355\u53f7'),
        ),
    ]
