# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0017_auto_20190228_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u59d3\u540d'),
        ),
    ]
