# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-06 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0018_auto_20190228_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='units',
        ),
    ]
