# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0019_remove_specimen_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='invoice',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='\u53d1\u7968\u53f7'),
        ),
        migrations.AlterField(
            model_name='peptide',
            name='CRO_company',
            field=models.CharField(choices=[('gl', '\u5409\u5c14'), ('cp', '\u4e2d\u80bd')], default='gl', max_length=50, verbose_name='\u5916\u5305\u516c\u53f8\u540d\u79f0'),
        ),
    ]
