# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoatigen', '0020_auto_20190308_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973'), ('unknown', '*')], default='unknown', max_length=10, verbose_name='\u6027\u522b'),
        ),
    ]
