# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neoatigen', '0021_auto_20190308_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.FileField(upload_to='patient/%Y/%m', verbose_name='\u4e0a\u4f20\u6587\u4ef6')),
                ('file_type', models.CharField(choices=[('pic', '\u56fe\u7247'), ('pdf', 'PDF'), ('others', '\u5176\u5b83')], max_length=10, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('category', models.CharField(blank=True, choices=[('apply', '\u75ab\u82d7\u7533\u8bf7\u5355'), ('MedRecord', '\u75c5\u5386'), ('invoice', '\u53d1\u7968'), ('express', '\u5feb\u9012\u5355')], max_length=20, null=True, verbose_name='\u7c7b\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('patient', models.ManyToManyField(blank=True, null=True, to='neoatigen.Patient', verbose_name='\u5bf9\u5e94\u75c5\u4eba')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20',
                'verbose_name_plural': '\u6587\u4ef6\u4e0a\u4f20',
            },
        ),
    ]
