# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='name',
            field=models.FileField(default='', max_length=50, upload_to=b'', verbose_name='\u6587\u4ef6\u540d'),
        ),
    ]
