# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadfile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='download',
            new_name='upload_file',
        ),
    ]
