# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20190308_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u6587\u4ef6\u540d'),
        ),
    ]
